module.exports = [
    {dropdownOption: '@radeonPrographicsDDSelector', subMenuOption: '@proGraphicsSubArchitectureEngineeringConstruction', expectedHeader: 'Architecture, Engineering and Construction'},
    {dropdownOption: '@radeonPrographicsDDSelector', subMenuOption: '@proGraphicsSubDesignManufacturing', expectedHeader: 'Design and Manufacturing'},
    {dropdownOption: '@radeonPrographicsDDSelector', subMenuOption: '@proGraphicsSubMediaEntertainment', expectedHeader: 'Media and Entertainment'},
    {dropdownOption: '@radeonPrographicsDDSelector', subMenuOption: '@proGraphicsSubPartners', expectedHeader: 'Radeon™ Pro Workstation Partners'},
    {dropdownOption: '@radeonPrographicsDDSelector', subMenuOption: '@proGraphicsSubRadeonProWorkstationGraphicsSelector', expectedHeader: 'AMD Radeon™ Pro Workstation Graphics Selector'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubRadeonInstinctAccelerators', expectedHeader: 'AMD Instinct™ MI Series Accelerators'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubRocM', expectedHeader: 'AMD ROCm™ Open Ecosystem'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubDeepLearning', expectedHeader: 'AMD Instinct™ GPU-Powered Machine Learning Solutions'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubGpuCompute', expectedHeader: 'AMD Instinct™ GPU-Powered HPC Solutions'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubVirtualGraphics', expectedHeader: 'Virtual Graphics'},
    {dropdownOption: '@radeonServerSolutionsDDSelector', subMenuOption: '@gServerSolutionsSubPartners', expectedHeader: 'Radeon™ Pro Workstation Partners'},
    {dropdownOption: '@radeonSoftwareDDSelector', subMenuOption: '@gRadeonSoftwareSubGaming', expectedHeader: 'Gaming with Radeon™ Software'},
    {dropdownOption: '@radeonSoftwareDDSelector', subMenuOption: '@gRadeonSoftwareSubStreaming', expectedHeader: 'Radeon™ Software: Streaming'},
    {dropdownOption: '@radeonSoftwareDDSelector', subMenuOption: '@gRadeonSoftwareSubPerformance', expectedHeader: 'Radeon™ Software: Performance'},
    {dropdownOption: '@radeonSoftwareDDSelector', subMenuOption: '@gRadeonSoftwareSubApu', expectedHeader: 'Radeon™ Software for AMD Ryzen™ Processors with Radeon™ Graphics'},
    {dropdownOption: '@radeonSoftwareDDSelector', subMenuOption: '@gRadeonSoftwareSubVanguardBetaTesters', expectedHeader: 'AMD Radeon™ Software Vanguard Beta Testers'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubImageQuality', expectedHeader: 'AMD Radeon™ Pro Software Image Quality'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubQuality', expectedHeader: 'AMD Radeon™ Pro Software Quality'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubPerformance', expectedHeader: 'AMD Radeon™ Pro Software Performance'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubDayZeroCertification', expectedHeader: 'AMD Radeon™ Pro Software Day Zero Certification'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubRemoteWorkstation', expectedHeader: 'AMD Remote Workstation'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubRadeonProRelive', expectedHeader: 'AMD Radeon™ Pro ReLive'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubWirelessProVr', expectedHeader: 'AMD Radeon™ Pro Software Wireless VR'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubRadeonProSettings', expectedHeader: 'AMD Radeon™ Pro Settings'},
    {dropdownOption: '@radeonProSoftwareDDSelector', subMenuOption: '@gRadeonProSoftSubHowToVideos', expectedHeader: 'AMD Radeon™ Pro Software How-To Videos'},
    //{dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubForDevs', expectedHeader: 'NO HEADER/ NO HOMEPAGE BUTTON'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubHowToVideos', expectedHeader: 'AMD Radeon™ ProRender How-To Videos'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubDownloads', expectedHeader: 'AMD Radeon™ ProRender Downloads'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubAccaEdifus', expectedHeader: 'ACCA® Software Edificius'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSub3dsMax', expectedHeader: 'AMD Radeon™ ProRender for Autodesk® 3ds Max®'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubMaya', expectedHeader: 'AMD Radeon™ ProRender for Autodesk® Maya®'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubBlender', expectedHeader: 'AMD Radeon™ ProRender for Blender®'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubCinema4D', expectedHeader: 'MAXON Cinema 4D™'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubHoudini', expectedHeader: 'AMD Radeon™ ProRender for SideFX® Houdini™'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubModo', expectedHeader: 'Foundry® Modo®'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubSolidWorks', expectedHeader: 'Radeon™ Pro Workstation Cards Certified for Dassault Systèmes® SOLIDWORKS®'},
    {dropdownOption: '@radeonProRenderDDSelector', subMenuOption: '@gRadeonProRenderSubUnrealEngine', expectedHeader: 'AMD Radeon™ ProRender for Unreal® Engine'},
    {dropdownOption: '@graphicsEmbeddedDDSelector', subMenuOption: '@gEmbeddedSubRadeonHighPerformance', expectedHeader: 'AMD High-Performance Embedded GPUs'},
    {dropdownOption: '@graphicsEmbeddedDDSelector', subMenuOption: '@gEmbeddedSubRadeonPowerEfficient', expectedHeader: 'AMD Power-Efficient Embedded GPUs'},
    {dropdownOption: '@graphicsEmbeddedDDSelector', subMenuOption: '@gEmbeddedSubRadeonUltraHighPerformance', expectedHeader: 'AMD Ultra-High-Performance Embedded GPUs'},
    {dropdownOption: '@graphicsEmbeddedDDSelector', subMenuOption: '@gEmbeddedSubAppSpecSolutions', expectedHeader: 'AMD Embedded Solutions'},
    

]