module.exports = [
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubRyzenThreadripper', expectedHeader: 'AMD Ryzen™ Threadripper™ Processors'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubRyzen', expectedHeader: 'AMD Ryzen™ Desktop Processors'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubRyzenWithGraphics', expectedHeader: 'AMD Ryzen™ Desktop Processors with Radeon™ Graphics'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubAthlonWithGraphics', expectedHeader: 'AMD Athlon™ Desktop Processors with Radeon™ Graphics'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubBuRyzenPro', expectedHeader: 'AMD Ryzen™ Desktop Processors with PRO technologies'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubBuAthlonPro', expectedHeader: 'AMD Athlon™ Desktop Processors with PRO technologies'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubBuAmdProTechnologies', expectedHeader: 'AMD PRO Technologies'},
    {dropdownOption: '@desktopDDSelector', subMenuOption: '@desktopSubBuBusinessPcs', expectedHeader: 'Where to Buy AMD Ryzen™ PRO Powered Laptops and Enterprise Systems'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubRyzen', expectedHeader: 'AMD Ryzen™ Mobile Processors with Radeon™ Graphics'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubAthlon', expectedHeader: 'AMD Athlon™ Mobile Processors with Radeon™ Graphics'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubChromebook', expectedHeader: 'AMD Powered Chromebooks'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubBuRyzen', expectedHeader: 'AMD Ryzen™ PRO and AMD Ryzen™ Mobile Processors for Business'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubBuAmdProTechnologies', expectedHeader: 'AMD PRO Technologies'},
    {dropdownOption: '@laptopDDSelector', subMenuOption: '@laptopSubBusinessPcs', expectedHeader: 'Where to Buy AMD Ryzen™ PRO Powered Laptops and Enterprise Systems'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubArchitecture', expectedHeader: 'AMD Ryzen™ Threadripper™ PRO Processors For Architects'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubDesignManufacturing', expectedHeader: 'AMD Ryzen™ Threadripper™ PRO Processors For Engineers'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubMediaEntertainment', expectedHeader: 'AMD Ryzen™ Threadripper™ PRO Processors For VFX Artists'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubSoftwareSciences', expectedHeader: 'AMD Ryzen™ Threadripper™ PRO Processors For Software and Sciences'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubWhereToBuy', expectedHeader: 'Where to Buy AMD Powered Workstations'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubRyzenThreadripperPro', expectedHeader: 'AMD Ryzen™ Threadripper™ PRO 3000WX Series Processors'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubRyzenThreadripper', expectedHeader: 'AMD Ryzen™ Threadripper™ Processors For Creators'},
    {dropdownOption: '@workstationDDSelector', subMenuOption: '@workstationSubRyzen', expectedHeader: 'AMD Ryzen™ Processors for Creators'},
    {dropdownOption: '@embeddedDDSelector', subMenuOption: '@pEmbeddedSubEpyc', expectedHeader: 'AMD™ EPYC Embedded Family'},
    {dropdownOption: '@embeddedDDSelector', subMenuOption: '@pEmbeddedSubRyzen', expectedHeader: 'AMD Ryzen™ Embedded Family'},
    {dropdownOption: '@embeddedDDSelector', subMenuOption: '@pEmbeddedSubGSeries', expectedHeader: 'AMD Embedded G-Series Family'},
    {dropdownOption: '@embeddedDDSelector', subMenuOption: '@pEmbeddedSubRSeries', expectedHeader: 'AMD Embedded R-Series Family'},
    {dropdownOption: '@embeddedDDSelector', subMenuOption: '@pEmbeddedSubAppSpecSolutions', expectedHeader: 'AMD Embedded Solutions'}
]